%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%               NOTHING TO BE CHANGED BELOW THIS LINE!!!!
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%% DATA PREPARATION %%%%%%%%%%%%%%%%%%%%%%
% this line says that if you want to calculate the individual sta's, 
% use the spikeburstforindividualspikesta
function sta_5_masterTRY(data, strTopFile, origFileName, nameHN)

%%% load constants
[sta_method, invertCorrectionTrace, invertTriggeringTrace, ...
NdiscardFirst, NdiscardLast, IntervalPosLocal, IntervalNegLocal, ...
IntervalPos, IntervalNeg, IntervalPos2, IntervalNeg2, IntervalPSCNeg, ...
ISIburst, thresh, peak, Trefractory, CorrectionTrace, CT, CalcMin, ...
spike_subtractor, spike_adder, Overlay, DataNames, x_label, yL, yH, ...
xlabel1, ylabel1, FntS, TracesPerPage, NBurstsStat, PrintNext] = ...
        askWinSTA_1_global(nameHN);
 
%%% prepare data for plot of voltages
[minTimeH,  maxTimeH, minVH, maxVH, tT, V, dataSP, FalseSpike, ...
    burSPKtimes_med, burSPKvolt_med, indexLR_ofBursts] = ...
        prepareDataForSTA0(CT, invertTriggeringTrace, ...
            invertCorrectionTrace, data, ISIburst, Trefractory, thresh, ...
            peak, sta_method, spike_subtractor, spike_adder);

%%% now create a figure that plots the voltage trace, along with the 
%%% detected spikes and the lower and upper thresholds
plotVoltageTraces(tT, V, x_label, DataNames, minTimeH, maxTimeH, ...
       minVH, maxVH, thresh, peak, dataSP(:,3), FalseSpike, CT,...
       burSPKtimes_med, burSPKvolt_med);
   
disp('******* GLOBAL DATA USED **********')
displayGlobalDataUsed(sta_method, invertCorrectionTrace, ...
    invertTriggeringTrace, NdiscardFirst, NdiscardLast, IntervalPosLocal, ...
    IntervalNegLocal, IntervalPos, IntervalNeg, IntervalPos2, ...
    IntervalNeg2, IntervalPSCNeg, ISIburst, thresh, peak, Trefractory, ...
    CorrectionTrace, CT, CalcMin, spike_subtractor, spike_adder, Overlay, ...
    DataNames, x_label, yL, yH, xlabel1, ylabel1, FntS, TracesPerPage, ...
    NBurstsStat, PrintNext);
disp('***********************************')



end
